### ISSUE TITLE
Изменение счётчика цикла внутри цикла

### ISSUE THREAD

**Issue by spogozhev** [sallyrain/Practice-pm-pu#2]
https://github.com/sallyrain/Practice-pm-pu/blob/8ec61cb34a0674c0b471994394a5e19409d17b22/Homework/15.11.21/Matrix.h#L26-L27

Происходит изменение переменной k, которая выступает в роли счётчика для цикла for внутри того же цикла.

**Comment by sallyrain** [comment]
changed the name of the k to kofi.
